sudo: required
dist: trusty
language: python
services:
- docker
env:
  global:
  - IMAGE_NAME=rtpengine-docker
  - COMMIT=${TRAVIS_COMMIT::7}
  - MAJ_VERSION="3.2"
install: true
script:
- docker build -t readytalk/$IMAGE_NAME:$MAJ_VERSION.$TRAVIS_BUILD_NUMBER-$COMMIT
  .
- docker images
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push readytalk/$IMAGE_NAME:$MAJ_VERSION.$TRAVIS_BUILD_NUMBER-$COMMIT
notifications:
  slack:
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}> by %{author} %{result} in %{duration}"
      - "Image Name: readytalk/rtpengine-docker:3.2.%{build_number}-%{commit}"
    on_success: always # default: always
    on_failure: always # default: always
    rooms:
      - secure: iHclNGXQuE5hKct86ewvLSb/q5M/BeFwjMUwQWJ2Knbi1tgORhw7F81wQhgtpSKrnkB+yScBlpI84mGHXXFFoGUXO925/Ed086WCFwbVb/1SXWJQMuuRuH2H6S7bMV9dCMr/X4hSBMfk7MUhI17BPd/OgHwtyoH8mdI1BJ1HeCmNG3EQuf00zNcbgUIeMZXYpPXz8TuWuSqK0i1uZRES3D6I8MKBH92djVwMaK3cUJ85DKn8/oAnnda7xef+WVHad0/NqwG4Qo0SpF+xPcxMof9nqvsHUmIXuYhJDRqJXOcWdZDXUxHT2y4vDYwQvywLyShCUfylxsEJRXJVJevq6UGvqTiK/2EV0iom+ptHSNa9RFzk/N9rgWr+sPLCec4xtWK4uP6zFdnx4/KFDCV+t58kOjx8U9P83NhP7N/7JH6kIsKwcrLYx84+7yFlEbjcnDcy5K5svEy58ikNeftgKxV82+/KSN3u82OQorQQmNm0R1cPVONR8DvD09pj0+t8f0Sxsapht7/Vqpga6bP15UJ+ZizHR5E6RzAjKBRqPlLJEF7MKcGqLCCDndqR/5Vrqkuxo8t0zgcV7hcOuCw+SkXSX2vqxX3v7jNoMKzogkstfc8yL2RoKB97gyF+HBMGSHL10jyfHOIkh4AnJLeW0OF9Vx2p1yzHK95JvFsMIhs=
